name: Container image

on:
  push:
    branches: ["main"]
    tags:
       - '**'
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Deploy caprover
        uses: josedev-union/caprover-compose-action@main
        with:
          server: ${{ secrets.CAPTAIN_SERVER_URL }}
          password: ${{ secrets.CAPTAIN_SERVER_PASSWORD }}
